# Generated by Django 3.0.8 on 2020-07-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(choices=[('1', 'Clint'), ('2', 'Ben Dover'), ('3', 'Ian')], max_length=1)),
            ],
        ),
    ]
